version: '3.8'

services:
  docs:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    ports:
      - "3300:3000"
    environment:
      - NODE_ENV=development
    # Add healthcheck to ensure the service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    stdin_open: true
    tty: true

volumes:
  mintlify_cache: